# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: example/rpc/haberdasher/service.proto

from typing import Any

from twirp.client import TwirpClient
from twirp.context import Context

from example.rpc.haberdasher import service_pb2 as _service_pb2


class HaberdasherClient(TwirpClient):

	def MakeHat(
		self,
		*,
		ctx: Context,
		request: _service_pb2.Size,
		server_path_prefix: str = "/twirp",
		**kwargs: Any
	) -> _service_pb2.Hat:
		return self._make_request(
			url=F"{server_path_prefix}/twitch.twirp.example.Haberdasher/MakeHat",
			ctx=ctx,
			request=request,
			response_obj=_service_pb2.Hat,
			**kwargs,
		)
