# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: example/rpc/haberdasher/service.proto

from typing import Protocol

from twirp.context import Context
from twirp.endpoint import Endpoint
from twirp.server import TwirpServer

from example.rpc.haberdasher import service_pb2 as _service_pb2


class HaberdasherServiceProtocol(Protocol):
	async def MakeHat(self, ctx: Context, request: _service_pb2.Size) -> _service_pb2.Hat: ...

class HaberdasherServer(TwirpServer):
	def __init__(
		self,
		*,
		service: HaberdasherServiceProtocol,
		server_path_prefix: str = "/twirp"
	):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/twitch.twirp.example.Haberdasher"
		self._endpoints = {
			"MakeHat": Endpoint(
				service_name="Haberdasher",
				name="MakeHat",
				function=getattr(service, "MakeHat"),
				input=_service_pb2.Size,
				output=_service_pb2.Hat,
			),
		}
