# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: example/rpc/haberdasher/service.proto

from typing import Any

from aiohttp import ClientSession
from twirp.async_client import AsyncTwirpClient
from twirp.context import Context

from example.rpc.haberdasher import service_pb2 as _service_pb2


class AsyncHaberdasherClient(AsyncTwirpClient):

	async def MakeHat(
		self,
		*,
		ctx: Context,
		request: _service_pb2.Size,
		server_path_prefix: str = "/twirp",
		session: ClientSession | None =None,
		**kwargs: Any
	) -> _service_pb2.Hat:
		return await self._make_request(
			url=F"{server_path_prefix}/twitch.twirp.example.Haberdasher/MakeHat",
			ctx=ctx,
			request=request,
			response_obj=_service_pb2.Hat,
			session=session,
			**kwargs,
		)
