package generator

import "text/template"

// TwirpTemplate - Template for twirp server and client
var TwirpTemplate = template.Must(template.New("TwirpTemplate").Parse(`# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: {{.FileName}}

from google.protobuf import symbol_database as _symbol_database

from typing import Any, Protocol
from twirp.client import TwirpClient
from twirp.context import Context
from twirp.endpoint import Endpoint
from twirp.server import TwirpServer

try:
	from aiohttp import ClientSession
	from twirp.async_client import AsyncTwirpClient
	_async_available = True
except ModuleNotFoundError:
	_async_available = False

{{ range .Imports}}
{{if .From}}from {{.From}} {{end}}import {{.Import}} as {{.Alias}}
{{- end}}

_sym_db = _symbol_database.Default()
{{range .Services}}
class {{.Name}}ServiceProtocol(Protocol):
	{{- range .Methods }}
	async def {{.Name}}(self, ctx: Context, request: {{.QualifiedInput}}) -> {{.QualifiedOutput}}: ...
	{{- end }}

class {{.Name}}Server(TwirpServer):
	def __init__(
		self,
		*,
		service: {{.Name}}ServiceProtocol,
		server_path_prefix: str = "/twirp"
	):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/{{.ServiceURL}}"
		self._endpoints = { {{- range .Methods }}
			"{{.Name}}": Endpoint(
				service_name="{{.ServiceName}}",
				name="{{.Name}}",
				function=getattr(service, "{{.Name}}"),
				input={{.QualifiedInput}},
				output={{.QualifiedOutput}},
			),{{- end }}
		}

class {{.Name}}Client(TwirpClient):
{{range .Methods}}
	def {{.Name}}(
		self,
		*,
		ctx: Context,
		request: {{.QualifiedInput}},
		server_path_prefix: str = "/twirp",
		**kwargs: Any
	) -> {{.QualifiedOutput}}:
		return self._make_request(
			url=F"{server_path_prefix}/{{.ServiceURL}}/{{.Name}}",
			ctx=ctx,
			request=request,
			response_obj={{.QualifiedOutput}},
			**kwargs,
		)
{{end}}

if _async_available:
	class Async{{.Name}}Client(AsyncTwirpClient):
{{range .Methods}}
		async def {{.Name}}(
			self,
			*,
			ctx: Context,
			request: {{.QualifiedInput}},
			server_path_prefix: str = "/twirp",
			session: ClientSession | None =None,
			**kwargs: Any
		) -> {{.QualifiedOutput}}:
			return await self._make_request(
				url=F"{server_path_prefix}/{{.ServiceURL}}/{{.Name}}",
				ctx=ctx,
				request=request,
				response_obj={{.QualifiedOutput}},
				session=session,
				**kwargs,
			)
{{end}}{{end}}`))
