package generator

import "text/template"

// TwirpServerTemplate - Template for twirp server
var TwirpServerTemplate = template.Must(template.New("TwirpServerTemplate").Parse(`# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: {{.FileName}}

from typing import Protocol

from google.protobuf import symbol_database as _symbol_database
from twirp.context import Context
from twirp.endpoint import Endpoint
from twirp.server import TwirpServer
{{ range .Imports}}
{{if .From}}from {{.From}} {{end}}import {{.Import}} as {{.Alias}}
{{- end}}

_sym_db = _symbol_database.Default()
{{range .Services}}
class {{.Name}}ServiceProtocol(Protocol):
	{{- range .Methods }}
	async def {{.Name}}(self, ctx: Context, request: {{.QualifiedInput}}) -> {{.QualifiedOutput}}: ...
	{{- end }}

class {{.Name}}Server(TwirpServer):
	def __init__(
		self,
		*,
		service: {{.Name}}ServiceProtocol,
		server_path_prefix: str = "/twirp"
	):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/{{.ServiceURL}}"
		self._endpoints = { {{- range .Methods }}
			"{{.Name}}": Endpoint(
				service_name="{{.ServiceName}}",
				name="{{.Name}}",
				function=getattr(service, "{{.Name}}"),
				input={{.QualifiedInput}},
				output={{.QualifiedOutput}},
			),{{- end }}
		}
{{end}}`))

// TwirpClientTemplate - Template for twirp client
var TwirpClientTemplate = template.Must(template.New("TwirpClientTemplate").Parse(`# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: {{.FileName}}

from typing import Any

from google.protobuf import symbol_database as _symbol_database
from twirp.client import TwirpClient
from twirp.context import Context
{{ range .Imports}}
{{if .From}}from {{.From}} {{end}}import {{.Import}} as {{.Alias}}
{{- end}}

_sym_db = _symbol_database.Default()
{{range .Services}}
class {{.Name}}Client(TwirpClient):
{{range .Methods}}
	def {{.Name}}(
		self,
		*,
		ctx: Context,
		request: {{.QualifiedInput}},
		server_path_prefix: str = "/twirp",
		**kwargs: Any
	) -> {{.QualifiedOutput}}:
		return self._make_request(
			url=F"{server_path_prefix}/{{.ServiceURL}}/{{.Name}}",
			ctx=ctx,
			request=request,
			response_obj={{.QualifiedOutput}},
			**kwargs,
		)
{{end}}{{end}}`))

// TwirpAsyncClientTemplate - Template for twirp client
var TwirpAsyncClientTemplate = template.Must(template.New("TwirpAsyncClientTemplate").Parse(`# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: {{.FileName}}

from typing import Any

from aiohttp import ClientSession
from google.protobuf import symbol_database as _symbol_database
from twirp.async_client import AsyncTwirpClient
from twirp.context import Context
{{ range .Imports}}
{{if .From}}from {{.From}} {{end}}import {{.Import}} as {{.Alias}}
{{- end}}

_sym_db = _symbol_database.Default()
{{range .Services}}
class Async{{.Name}}Client(AsyncTwirpClient):
{{range .Methods}}
	async def {{.Name}}(
		self,
		*,
		ctx: Context,
		request: {{.QualifiedInput}},
		server_path_prefix: str = "/twirp",
		session: ClientSession | None =None,
		**kwargs: Any
	) -> {{.QualifiedOutput}}:
		return await self._make_request(
			url=F"{server_path_prefix}/{{.ServiceURL}}/{{.Name}}",
			ctx=ctx,
			request=request,
			response_obj={{.QualifiedOutput}},
			session=session,
			**kwargs,
		)
{{end}}{{end}}`))
